### ISSUE TITLE
Sorting by drag'n drop

### ISSUE THREAD

**Issue by fdav087** [spillz/picty#19]
Hi,
is it possible to sort by moving the images relative to each other ? thus, we can change the metadata (date / time for example) more easily?

**Comment by spillz** [comment]
That wouldn't be a simple change and I am not sure how you would get fine
grained control over dates that way. Do you have an example?

A more straightforward thing would be to add a plugin that allows right
click -> change dates on single item or selection. Or just integrate the
feature into the other metadata editing.

**Comment by fdav087** [comment]
Suppose we have 10 photos; they come from different cameras with different times. I display them sorted by shooting first then I position the sort criterion on "manual". A serial number is set on each photo in memory, from 1 to 10 in our example. I slide 9 after 2; the 9 becomes 3 and I roll out all the following ones (the 3 becomes 4, the 4 becomes 5, ...). All this in memory. Thus, I can modify the metadata (dates / place, ...) of each photo in the established order.
After that :
- I could save the order number of each photo as a tag (or some other way, to continue my ranking later for example)
- I could bulk rename my photos

Outside of adobe or acdsee, I do not know which allow manual sorting ...

Changing the metadata could be done as mp3tag (https://www.mp3tag.de/en/) or PDFexplorer (http://www.rttsoftware.com/) but that is another subject.

**Comment by spillz** [comment]
So one thing I have thought about in the past is the concept of having
groups or baskets of images. This is not much different from having a set
of images with a common tag but I would add a "group view" where you could
sort images in the group using drag and drop and that custom sort would be
persistent.

**Comment by fdav087** [comment]
Exactly, it would be a plus ...
in fact, luckily, my photos taken with my smartphone had the correct time zone and the right time but I had not changed my Canon Reflex ..., suddenly, I am obliged to classify them by hand and modify the tags (geotag, time, ...)
